=== Genevjov/Practice7/src/input.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/input"
	xmlns:tns="http://www.example.org/input" elementFormDefault="qualified">

	<element name="Tariffs">
		<complexType>
			<sequence maxOccurs="unbounded">
				<element name="Tariff" type="tns:Tariff" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Tariff">
		<sequence>
			<element name="OperatorName" type="string" />
			<element name="TariffName" type="string" />
			<element name="PayRoll" type="float" />
			<element name="SmsPrice" type="float" />
			<element name="CallPrice" type="tns:CallPriceInfo" />
			<element name="Parameters" type="tns:ParametersInfo" />
		</sequence>
	</complexType>

	<complexType name="ParametersInfo">
		<sequence>
			<element name="LovelyNumberRresence">
				<simpleType>
					<restriction base="decimal">
						<minInclusive value="0" />
						<maxInclusive value="9999" />
					</restriction>
				</simpleType>
			</element>
			<element name="Tariffication">
				<simpleType>
					<restriction base="decimal">
						<enumeration value="12" />
						<enumeration value="60" />
					</restriction>
				</simpleType>
			</element>

			<element name="ConnectionPrice">
				<simpleType>
					<restriction base=" decimal">
						<minInclusive value="0" />
						<maxInclusive value="9999" />
					</restriction>
				</simpleType>
			</element>

		</sequence>

	</complexType>

	<simpleType name="CallPrice">
		<restriction base="float">
			<minInclusive value="0" />
			<maxInclusive value="99999" />
		</restriction>
	</simpleType>

	<complexType name="CallPriceInfo">
		<sequence>
			<element name="WithinNetworkCallPrice" type="tns:CallPrice" />
			<element name="OutOfNetworkCallPrice" type="tns:CallPrice" />
			<element name="LandLineNumCallPrice" type="tns:CallPrice" />
		</sequence>
	</complexType>

</schema>

=== Genevjov/Practice7/output.sax.xml
<?xml version="1.0" ?>
<tns:Tariffs xmlns:tns="http://www.example.org/output"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/input input.xsd">
	<tns:Tariff>
		<tns:OperatorName>tns:OperatorName</tns:OperatorName>
		<tns:TariffName>tns:TariffName</tns:TariffName>
		<tns:PayRoll>0.0</tns:PayRoll>
		<tns:SmsPrice>0.0</tns:SmsPrice>
		<tns:CallPrice>
			<tns:WithinNetworkCallPrice>0.0</tns:WithinNetworkCallPrice>
			<tns:OutOfNetworkCallPrice>0.0</tns:OutOfNetworkCallPrice>
			<tns:LandLineNumCallPrice>0.0</tns:LandLineNumCallPrice>
		</tns:CallPrice>
		<tns:Parameters>
			<tns:LovelyNumberRresence>1</tns:LovelyNumberRresence>
			<tns:Tariffication>12</tns:Tariffication>
			<tns:ConnectionPrice>0.0</tns:ConnectionPrice>
		</tns:Parameters>
	</tns:Tariff>
	<tns:Tariff>
		<tns:OperatorName>LifeCell</tns:OperatorName>
		<tns:TariffName>life Hack</tns:TariffName>
		<tns:PayRoll>0.0</tns:PayRoll>
		<tns:SmsPrice>11.0</tns:SmsPrice>
		<tns:CallPrice>
			<tns:WithinNetworkCallPrice>1.0</tns:WithinNetworkCallPrice>
			<tns:OutOfNetworkCallPrice>2.0</tns:OutOfNetworkCallPrice>
			<tns:LandLineNumCallPrice>3.0</tns:LandLineNumCallPrice>
		</tns:CallPrice>
		<tns:Parameters>
			<tns:LovelyNumberRresence>17</tns:LovelyNumberRresence>
			<tns:Tariffication>12</tns:Tariffication>
			<tns:ConnectionPrice>0.0</tns:ConnectionPrice>
		</tns:Parameters>
	</tns:Tariff>
</tns:Tariffs>
